### PR TITLE
Claim supporting `textDocument/semanticTokens` capability

### PR DESCRIPTION
**Pull request by jfcherng**
@litezzzout After this, Pylance does semantic highlighting. Copied from what VSCode sends to Pylance.

### CODE REVIEW

**Comment by litezzzout** [comment]
> @litezzzout After this, Pylance does semantic highlighting. Copied from what VSCode sends to Pylance.

pylance doesn't work with `get_capability('semanticTokensProvider')['legend']['tokenTypes']` ?

**Comment by jfcherng** [comment]
> > @litezzzout After this, Pylance does semantic highlighting. Copied from what VSCode sends to Pylance.
> 
> pylance doesn't work with `get_capability('semanticTokensProvider')['legend']['tokenTypes']` ?

If you don't claim your client support `textDocument/semanticTokens` capability, then no, Pylance won't tell you it supports `semanticTokensProvider` either.

**Comment by litezzzout** [comment]
that behavior is specific to pylance? or other server do the same? cause clangd just worked. without doing this.

**Comment by jfcherng** [comment]
I think it's the standard. Otherwise, why we need these https://github.com/litezzzout/LSP/blob/f07c6a4788a610d23f1fd54fb9918f37565ad7c1/plugin/core/sessions.py#L127-L295

**Pull request merged**
